package lesson_07_abstract_class_and_interface.practice.bai_01_class_nimal_and_interface_edible.fruit;

import lesson_07_abstract_class_and_interface.practice.bai_01_class_nimal_and_interface_edible.edible.Edible;

public abstract class Fruit implements Edible { }
